// checksum 0xfde6 version 0x90005
/*
  This file was generated by the Qt Quick 2 Application wizard of Qt Creator.
  QtQuick2ApplicationViewer is a convenience class containing mobile device specific
  code such as screen orientation handling. Also QML paths and debugging are
  handled here.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef QTQUICK2APPLICATIONVIEWER_H
#define QTQUICK2APPLICATIONVIEWER_H

#include <QtQuick/QQuickView>

/**
 * @brief
 *
 */
class QtQuick2ApplicationViewer : public QQuickView
{
    Q_OBJECT

public:
    /**
     * @brief
     *
     * @param parent
     */
    explicit QtQuick2ApplicationViewer(QWindow *parent = 0);
    /**
     * @brief
     *
     */
    virtual ~QtQuick2ApplicationViewer();

    /**
     * @brief
     *
     * @param file
     */
    void setMainQmlFile(const QString &file);
    /**
     * @brief
     *
     * @param path
     */
    void addImportPath(const QString &path);

    /**
     * @brief
     *
     */
    void showExpanded();

private:
    class QtQuick2ApplicationViewerPrivate *d; /**< TODO */
};

#endif // QTQUICK2APPLICATIONVIEWER_H
